// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sakwaygbpigofzocimum.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNha3dheWdicGlnb2Z6b2NpbXVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NDY0MzIsImV4cCI6MjA3MzUyMjQzMn0.iavuLdgpWvGdgPVD00nVdyQZ3CwX8b1oXY8YRAM-DFM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});